name: kmodes-init
channels:
  - defaults
dependencies:
  - numpy=1.16.2
  - pandas=0.24.2
  - pip=19.0.3
  - python=3.7.0
  - scikit-learn=0.20.3
  - pip:
    - git+https://github.com/daffidwilde/edo_exp
    - git+https://github.com/daffidwilde/kmodes@dev
    - edo==0.2.1
    - matching==1.1
