name: kmodes-init
channels:
  - defaults
dependencies:
  - dask=1.2.0
  - matplotlib=3.1.1
  - numpy=1.16.2
  - pandas=0.24.2
  - pip=19.0.3
  - python=3.7.0
  - scikit-learn=0.20.3
  - scipy=1.3.1
  - pip:
    - git+https://github.com/daffidwilde/edo_exp@v0.0.11
    - git+https://github.com/daffidwilde/kmodes@v0.9.0
    - edo==0.2.1
    - matching==1.1
    - tqdm==4.36.1
    - yellowbrick==1.0.1
